// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs8uCKM7JLjEEqSzxwuzhXh8G2glSz0Iw',
    appId: '1:718933554689:web:c9c3cfeedd5c3379837200',
    messagingSenderId: '718933554689',
    projectId: 'musicapp-3b92e',
    authDomain: 'musicapp-3b92e.firebaseapp.com',
    storageBucket: 'musicapp-3b92e.firebasestorage.app',
    measurementId: 'G-G1FQG63GCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJdTuir5JxhAIX7I3ZgJw89R10x1rQDzQ',
    appId: '1:718933554689:android:11b7ad021bad76ed837200',
    messagingSenderId: '718933554689',
    projectId: 'musicapp-3b92e',
    storageBucket: 'musicapp-3b92e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbjIh9qhGuUEgmbEOxULKijxEQ-ZEz3nQ',
    appId: '1:718933554689:ios:f40d3ed649a56961837200',
    messagingSenderId: '718933554689',
    projectId: 'musicapp-3b92e',
    storageBucket: 'musicapp-3b92e.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbjIh9qhGuUEgmbEOxULKijxEQ-ZEz3nQ',
    appId: '1:718933554689:ios:6b6b46026a46e844837200',
    messagingSenderId: '718933554689',
    projectId: 'musicapp-3b92e',
    storageBucket: 'musicapp-3b92e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs8uCKM7JLjEEqSzxwuzhXh8G2glSz0Iw',
    appId: '1:718933554689:web:4636b5ece959ea00837200',
    messagingSenderId: '718933554689',
    projectId: 'musicapp-3b92e',
    authDomain: 'musicapp-3b92e.firebaseapp.com',
    storageBucket: 'musicapp-3b92e.firebasestorage.app',
    measurementId: 'G-EZG7QF7XF4',
  );
}
